name       : unixodbc
version    : 2.3.4
release    : 1
source     :
    - ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.4.tar.gz : 2e1509a96bb18d248bf08ead0d74804957304ff7c6f8b2e5965309c632421e39
license    : 
    - GPL-2.0
    - LGPL-2.1
component  : database
emul32     : yes
summary    : ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
description: |
    ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
