name       : unixodbc
version    : 2.3.5
release    : 2
source     :
    - ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.5.tar.gz : 760972e05cc6361aee49d676fb7da8244e0f3a225cd4d3449a951378551b495b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : database
emul32     : yes
summary    : ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
description: |
    ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
