name       : unixodbc
version    : 2.3.9
release    : 5
source     :
    - ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.9.tar.gz : 52833eac3d681c8b0c9a5a65f2ebd745b3a964f208fc748f977e44015a31b207
homepage   : https://www.unixodbc.org
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : database
emul32     : yes
summary    : ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
description: |
    ODBC is an open specification for providing application developers with a predictable API with which to access Data Sources
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
